### PR TITLE
Update enemyBehaviour.cs

### PR DESCRIPTION
**Pull request by radiatoryang**
reduced redundancy between 2 similar if statements

### CODE REVIEW

**Comment by connorallenkilpatrick** [comment]
_HMMMM_ idk about this guy...

**Comment by connorallenkilpatrick** [comment]
But approved :ok_hand:

**Comment by NickChirico** [comment]
I feel enlightened

**Comment by alb812** [comment]
I trust it

**Comment by rainekind** [comment]
i'm down with this

**Pull request merged**
